authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"

urlpatterns = [
    path('def_login/', views.default_login_view, name="def_login"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

cms/urls.py
from django.urls import path
from . import views

app_name = "cms"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('update-info/', views.update_info, name="update_info"),
    path('update-project/', views.update_project, name="update_project"),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.index, name="index"),
]

portfolio_cms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

handler404 = views.page_not_found_view
handler500 = views.server_error_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('edit/', include('cms.urls')),
    path('', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/views.py
from django.shortcuts import render
from information.models import (
    PersonalInfo,
    Project,
)

def index(request):
    return render(request, 'portfolio/index.html', {
        "info"      : PersonalInfo.objects.all().first(),
        "projects"  : Project.objects.all()
    })

portfolio/templates/portfolio/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ info.title }}</title>
    <link rel="shortcut icon" href="{% static 'icons/favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'styles/globalStyles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/indexStyles.css' %}">
</head>
<body>
    <div class="full-height d-flex">
        <div class="row">
            <div class="container-large col-lg-9 dark-bg light-grey-text full-height d-flex flex-col justify-content-between">
                <div id="info-container">
                    <div>
                        <h1 class="light-blue-text">{{ info.name }}</h1>
                    </div>
                    <div id="description">
                        <h3>{{ info.description }}</h3>
                    </div>
                </div>
                <div id="contact-container">
                    <div id="contact-links" class="line-wrapped">
                        <a href="{{ info.linkedin }}">
                            <img
                                src="{% static 'icons/linkedin.svg' %}"
                                alt="LinkedIn"
                                class="link-icon"
                            />
                        </a>
                        <a href="mailto: {{ info.email }}">
                            <img
                                src="{% static 'icons/email.svg' %}"
                                alt="Email"
                                class="link-icon"
                            />
                        </a>
                        <a href="tel:{{ info.phone_number }}">
                            <img
                                src="{% static 'icons/phone.svg' %}"
                                alt="Phone"
                                class="link-icon"
                            />
                        </a>
                    </div>
                </div>
            </div>
            <div class="container-small col-lg-3 light-bg full-height">
                <div class="text-right dark-blue-text">
                    <h2 class="section-title">Projects</h2>
                </div>
                {% for project in projects %}
                    <div>
                        {% if project.url %}
                            <a href="{{ project.url }}" class="medium-blue-text"><h4>{{ project.name }}</h4></a>
                        {% else %}
                            <a href="#" class="medium-blue-text"><h4>{{ project.name }}</h4></a>
                        {% endif %}
                        <h6 class="dark-grey-text">{{ project.description }}</h6>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="button-group dropup">
        <a class="dropdown-toggle btn-lg mode draw blue-bg" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="light-grey-text spaced">settings <i class="fa fa-angle-down fa-rotate-180"></i></span>
        </a>
        <div class="dropdown-menu light-bg light-grey-text" aria-labelledby="dropdownMenuButton">
            {% if not user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'authentication:def_login' %}">Log In</a>
            {% else %}
                <div>
                    <form class="" action="{% url 'authentication:logout' %}" method="POST">
                        {% csrf_token %}
                        <button class="dropdown-item" type="submit">Log Out</a>
                    </form>
                </div>
            {% endif %}
            <a class="dropdown-item" href="{% url 'cms:dashboard' %}">Edit Page</a>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>