authentication/urls.py
from django.urls import path
from . import views

app_name = "authentication"

urlpatterns = [
    path('def_login/', views.default_login_view, name="def_login"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

cms/urls.py
from django.urls import path
from . import views

app_name = "cms"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('update-info/', views.update_info, name="update_info"),
    path('update-project/', views.update_project, name="update_project"),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.index, name="index"),
]

portfolio_cms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from . import views

handler404 = views.page_not_found_view
handler500 = views.server_error_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('edit/', include('cms.urls')),
    path('', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/forms.py
from django import forms
from information.models import (
    PersonalInfo,
    Project,
)
from django.forms import modelformset_factory

class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = PersonalInfo 
        fields = "__all__"
        labels = {
            "name" : "Name",
            "description" : "Description",
            "email" : "E-mail",
            "linkedin" : "LinkedIn",
            "git" : "Git",
            "phone_number" : "Phone",
            "title" : "Site Name"
        }

        widgets = {
            "name" : forms.TextInput(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "Your Name"
                }
            ),
            "description" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "About You",
                    "rows" : 8
                }
            ),
            "email" : forms.EmailInput(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "Your E-mail Address"
                }
            ),
            "linkedin" : forms.URLInput(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "Your LinkedIn Profile"
                }
            ),
            "git" : forms.URLInput(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "Your Git URL"
                }
            ),
            "phone_number" : forms.TextInput(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "Your Phone Number"
                }
            ),
            "title" : forms.TextInput(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "Your Site Name"
                }
            )
        }

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = "__all__"
        labels = {
            "name" : "Project Name",
            "description" : "Project Description",
            "url" : "Project URL"
        },
        widgets = {
            "name" : forms.TextInput(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "Your Project Name"
                }
            ),
            "description" : forms.Textarea(
                attrs = {
                    "class" : "form-control",
                    "required" : True,
                    "placeholder" : "About the Project",
                    "rows" : 3
                }
            ),
            "url" : forms.URLInput(
                attrs = {
                    "class" : "form-control",
                    "required" : False,
                    "placeholder" : "Your Project URL"
                }
            ),
        }


ProjectModelFormSet = modelformset_factory(
    Project,
    fields= "__all__",
    extra=1,
    labels = {
        "name" : "Project Name",
        "description" : "Project Description",
        "url" : "Project URL"
    },
    widgets = {
        "name" : forms.TextInput(
            attrs = {
                "class" : "form-control",
                "required" : True,
                "placeholder" : "Your Project Name"
            }
        ),
        "description" : forms.Textarea(
            attrs = {
                "class" : "form-control",
                "required" : True,
                "placeholder" : "About the Project",
                "rows" : 3
            }
        ),
        "url" : forms.URLInput(
            attrs = {
                "class" : "form-control",
                "required" : False,
                "placeholder" : "Your Project URL"
            }
        ),
    }
)

cms/views.py
from django.shortcuts import render, redirect
from .forms import (
    PersonalInfoForm,
    ProjectForm,
    ProjectModelFormSet
)
from information.models import (
    PersonalInfo,
    Project,
)

from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import JsonResponse
from django.contrib import messages 
import json

@login_required(login_url="/auth/login")
def dashboard(request):
    personal_info = PersonalInfo.objects.all().first() 
    projects = Project.objects.all()
    return render(request, 'cms/dashboard.html', {
        "projects" : projects,
        "info" : personal_info,
        "info_form" : PersonalInfoForm(instance=personal_info),
        "project_form" : ProjectModelFormSet()
    })

def update_info(request):
    if request.method == "PUT" and request.is_ajax():
        current_instance = PersonalInfo.objects.all().first()
        data = json.loads(request.body)
        form = PersonalInfoForm({
            "name" : data["name"],
            "description" : data["description"],
            "email" : data["email"],
            "linkedin" : data["linkedin"],
            "git" : data["git"],
            "phone_number" : data["phone_number"],
            "title" : data["title"]
        }, instance=current_instance)

        if form.is_valid():
            form.save()
            return return_response(True)
        else:
            return return_response(False, form.errors)
    else:
        return_response(False, "Unallowed Method")

def update_project(request):
    if request.method == "POST":
        data = json.loads(request.body)
        form = ProjectForm({
            "name" : data["name"],
            "description" : data["description"],
            "url" : data["url"]
        })
        if form.is_valid():
            form.save()
            return JsonResponse({
                "success" : True,
                "message" : "Your info have been successfuly updated.",
                "url" : reverse('cms:dashboard')
            })
        else:
            return return_response(False, form.errors)
    elif request.method == "PUT" and request.is_ajax():
        data = json.loads(request.body)
        try:
            current_instance = Project.objects.filter(id=data['entryNo']).first()
            form = ProjectForm({
                "name" : data["name"],
                "description" : data["description"],
                "url" : data["url"]
            }, instance=current_instance)
        except: 
            form = ProjectForm({
                "name" : data["name"],
                "description" : data["description"],
                "url" : data["url"]
            })
        if form.is_valid():
            form.save()
            return return_response(True)
        else:
            return return_response(False, form.errors)
    elif request.method == "DELETE" and request.is_ajax():
        try:
            data = json.loads(request.body)
            current_instance = Project.objects.filter(id=data['entryNo']).first()
            current_instance.delete()
            return return_response(True)
        except Exception as e:
            return return_response(False, e)
    else:
        return return_response(False, "Unallowed Method")

def return_response(success, *argv):
    if success:
        return JsonResponse({
            "success" : True,
            "message" : "Your info have been successfuly updated."
        })
    else:
        return JsonResponse({
            "success" : False,
            "message" : argv[0],
        })

cms/templates/cms/dashboard.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ info.title }} Dashboard</title>
    <link rel="shortcut icon" href="{% static 'icons/favicon.ico' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/globalStyles.css' %}" >
    <link rel="stylesheet" href="{% static 'styles/dashboardStyles.css' %}" >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="container-large full-height d-flex light-bg light-grey-text">
        <div class="dark-blue-text w-100">
            <div id="information" class="d-flex flex-row justify-content-between">
                <div>
                    <h1>Dashboard</h1>
                </div>
                <div>
                    <div class="btn-lg mode draw blue-bg" onclick="exitDashboard()">
                        <span class="light-grey-text spaced">home</span>
                    </div>
                </div>
            </div>
            <div>
                <h2 class="medium-blue-text section-title">Personal Information</h2>
                <form class="site-form" action="" method="PUT" id="info-form">
                    {% csrf_token %}
                    {{ info_form }}
                    <div class="d-flex flex-row-reverse">
                        <button id="submit-button" class="btn mode draw blue-bg commit" onclick="updateInfo()">
                            <span class="light-grey-text">Save</span>
                        </button>
                    </div>
                </form>
            </div>
            <div id="projects">
                <h2 class="medium-blue-text section-title">Projects</h2>
                {% for form in project_form %}
                    {% if not forloop.first %}
                        <div class="spacer"></div>
                    {% endif %}
                    {% if not forloop.last %}
                        <div id="project-{{ form.instance.id }}">
                            <form class="site-form" action="" method="PUT" id="project-form-{{ form.instance.id }}">
                                {% csrf_token %}
                                {{ form }}
                                <div class="d-flex flex-row-reverse">
                                    <button id="submit-button" class="btn mode draw blue-bg commit" onclick="updateProject({{ form.instance.id }})">
                                        <span class="light-grey-text">Save</span>
                                    </button>
                                    <button id="submit-button" class="btn mode draw red-bg commit" onclick="deleteProject({{ form.instance.id }})">
                                        <span class="light-grey-text">Delete</span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    {% else %}
                        <div>
                            <h3 class="medium-blue-text">Add New Project</h3>
                            <form class="site-form" action="" method="POST" id="project-form-new">
                                {% csrf_token %}
                                {{ form }}
                                <div class="float-right">
                                    <button id="submit-button" class="btn mode draw blue-bg commit">
                                        <span class="light-grey-text" onclick="createProject()">Add</span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="modal fade" id="exit-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title medium-blue-text">Back to Home Page</h4>
                </div>
                <div class="modal-body">
                    <p id="exit-status">Do you wish to log out?</p>
                </div>
                <div class="modal-footer light-grey-text">
                    <a href="{% url 'portfolio:index' %}" class="btn btn-default light-grey-text blue-bg commit">No, Display my Page</a>
                    <div>
                        <form class="logout-form" action="{% url 'authentication:logout' %}" method="POST">
                            {% csrf_token %}
                            <button id="submit-button" class="btn btn-default dark-bg commit submit" type="submit">
                                    <span class="light-grey-text">Log Out</span>
                                </button>
                        </form>
                    </div>
                    <a class="btn btn-default red-bg commit" data-dismiss="modal">Cancel</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="response-modal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title medium-blue-text">Update Status</h4>
                </div>
                <div class="modal-body">
                    <p id="update-status"></p>
                </div>
                <div class="modal-footer light-grey-text">
                    <a href="{% url 'portfolio:index' %}" class="btn btn-default light-grey-text blue-bg commit">Home</a>
                    <a class="btn btn-default red-bg commit" data-dismiss="modal">Close</a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'scripts/info/updateInfo.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/project/createProject.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/project/updateProject.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/project/deleteProject.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/nav/exitDashboard.js' %}"></script>
</body>
</html>